name: 'QcmPlab setup action'
description: 'This is meant to be an OS & package independent action that contains the initial setup for the CI/CD workflows employed in QcmPlab repositories'

inputs:
  pack-type: 
    description: 'This input differentiate between MKL (mkl) and OpenBLAS (open) install'
    default: 'open'

#outputs:

runs:
  using: "composite" #this is needed
  steps:

#Linux
    - name: Mkl install ubuntu
    - run: sudo apt-get install intel-mkl-full
      if: ${{ runner.os == 'Linux' && inputs.pack-type == 'mkl' }}

    - name: open install ubuntu
    - run: sudo apt-get install libblas-dev liblapack-dev
      if: ${{ runner.os == 'Linux' && inputs.pack-type == 'open' }}

    - name: Linux openmpi
    - run:  sudo apt-get install -y openmpi-bin
      if: ${{ runner.os == 'Linux' }}

#MacOS
    - name: Mkl install ubuntu TO BE CORRECTED IT DOES NOW OPENBLAS
    - run: brew install lapack openblas
      if: ${{ runner.os == 'macOS' && inputs.pack-type == 'mkl' }}

    - name: Mkl install ubuntu
    - run: brew install lapack openblas
      if: ${{ runner.os == 'macOS' && inputs.pack-type == 'open' }}

    - name: install-openmpi
      run: brew install openmpi
      if: ${{ runner.os == 'macOS' }}


