name: Manually triggered CI workflow to execute unit tests

on: workflow_dispatch

jobs:
  test-ubuntu-20_04:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Cloning SciFortran
        run: git clone https://github.com/QcmPlab/SciFortran.git scifor

      - name: Install SciFortran
        run: ./inst_scifor.sh


      - name: Cloning DMFTtools
        run: git clone https://github.com/QcmPlab/DMFTtools.git DMFTtools

      - name: Install DMFTtools
        run: ./inst_DMFTtools.sh


      - name: Cloning LIB_DMFT_ED
        run: git clone https://github.com/QcmPlab/LIB_DMFT_ED.git LIB_DMFT_ED

      - name: Install LIB_DMFT_ED
        run: ./inst_LIB_DMFT_ED.sh
