name: Manually triggered CI workflow to execute unit tests

on: workflow_dispatch

jobs:
  test-ubuntu-20_04:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: gfortran-info
        run: gfortran --version

#Install BLAS and LAPACK
      - name: blas-n-lapack-install
        shell: bash -l {0}
        run: sudo apt-get install libblas-dev liblapack-dev

#Install OpenMPI
      - name: install-openmpi
        run: sudo apt-get install -y openmpi-bin
#      - name: download-openmpi
#        run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
#      - name: extract-openmpi
#        run: tar -xvf ./openmpi-4.0.2.tar.gz
#      - name: configure-openmpi
#        run: ./openmpi-4.0.2/configure --prefix="/home/${USER}/.openmpi"
#      - name: install-openmpi
#        run: |
#          make -j
#          sudo make install
      - name: set-openmpi-path
        shell: bash -l {0}
        run: |
          export PATH=${PATH}:/home/${USER}/.openmpi/bin/
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/${USER}/.openmpi/lib/
          echo ${PATH}
          echo ${LD_LIBRARY_PATH}


#Set up SciFortran
      - name: Cloning SciFortran
        shell: bash -l {0}
        run: git clone https://github.com/QcmPlab/SciFortran.git scifor
      - name: Install SciFortran
        shell: bash -l {0}
        run: ./inst_scifor.sh

#Set up DMFTtools
      - name: Cloning DMFTtools
        shell: bash -l {0}
        run: git clone https://github.com/QcmPlab/DMFTtools.git DMFTtools
      - name: Install DMFTtools
        shell: bash -l {0}
        run: ./inst_DMFTtools.sh

#Set up LIB_DMFT_ED
      - name: Cloning LIB_DMFT_ED
        shell: bash -l {0}
        run: git clone https://github.com/QcmPlab/LIB_DMFT_ED.git LIB_DMFT_ED
      - name: Install LIB_DMFT_ED
        shell: bash -l {0}
        run: ./inst_LIB_DMFT_ED.sh

#
# NEED TO INSERD THE UNIT TEST HERE
#



  test-macos-10_15:
    runs-on: macos-10.15

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#Reinstall gfortran
      - name: Required compiler
        run:  brew reinstall gfortran

      - name: gfortran-info
        run: gfortran --version

#Install BLAS and LAPACK
      - name: blas-n-lapack-install
        shell: bash -l {0}
        run: |
          alias gfortran='gfortran-9'
          brew install lapack openblas
          gfortran --version


#Install OpenMPI
      - name: install-openmpi
        run: brew install openmpi

#Set up SciFortran
      - name: Cloning SciFortran
        shell: bash -l {0}
        run: git clone https://github.com/QcmPlab/SciFortran.git scifor
      - name: Install SciFortran
        shell: bash -l {0}
        run: |
          alias gfortran='gfortran-9'
          ./inst_scifor.sh

#Set up DMFTtools
      - name: Cloning DMFTtools
        shell: bash -l {0}
        run: git clone https://github.com/QcmPlab/DMFTtools.git DMFTtools
      - name: Install DMFTtools
        shell: bash -l {0}
        run: ./inst_DMFTtools.sh

#Set up LIB_DMFT_ED
      - name: Cloning LIB_DMFT_ED
        shell: bash -l {0}
        run: git clone https://github.com/QcmPlab/LIB_DMFT_ED.git LIB_DMFT_ED
      - name: Install LIB_DMFT_ED
        shell: bash -l {0}
        run: ./inst_LIB_DMFT_ED.sh


