name: Manually triggered CI workflow to execute unit tests

on: workflow_dispatch

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-ubuntu-20_04:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: gfortran-info
        run: gfortran --version

#Install BLAS and LAPACK
      - name: blas-n-lapack-install
        run: sudo apt-get install libblas-dev liblapack-dev

#Install OpenMPI
      - name: install-openmpi
        run: sudo apt-get install -y openmpi-bin

#Set up SciFortran
      - name: Cloning SciFortran
        run: git clone https://github.com/QcmPlab/SciFortran.git scifor
      - name: Install SciFortran
        run: ./inst_scifor.sh

#Set up DMFTtools
      - name: Cloning DMFTtools
        run: git clone https://github.com/QcmPlab/DMFTtools.git DMFTtools
      - name: Install DMFTtools
        run: ./inst_DMFTtools.sh

#Set up LIB_DMFT_ED
      - name: Cloning LIB_DMFT_ED
        run: git clone https://github.com/QcmPlab/LIB_DMFT_ED.git LIB_DMFT_ED
      - name: Install LIB_DMFT_ED
        run: ./inst_LIB_DMFT_ED.sh

#Set up Slave_Spins
      - name: Cloning Slave_Spins
        run: git clone https://github.com/QcmPlab/Slave-Spins Slave_Spins
      - name: Install Slave_Spins
        run: ./inst_Slave_Spins.sh

#Testing
      - name: Building tests
        run:  |
          #source ~/.bashrc
          #export PKG_CONFIG_PATH=~/.pkgconfig.d
          #source ~/opt/scifor/gnu/*/bin/scifor_config_user.sh
          #source ~/opt/dmft_tools/gnu/*/bin/dmft_tools_config_user.sh
          #source ~/opt/dmft_ed/gnu/*/etc/dmft_ed_config.sh
          #source ~/opt/slave_spins/gnu/*/etc/slave_spins_config.sh
          export GLOB_INC=$( pkg-config --cflags dmft_ed dmft_tools scifor slave_spins)
          export GLOB_LIB=$( pkg-config --libs   dmft_ed dmft_tools scifor slave_spins | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          make all
        
      - name: Testing...
        run: make test



#Set up Drivers
      - name: Cloning Drivers
        run: git clone https://github.com/QcmPlab/Driver-Database.git Driver-Database
      - name: Install Drivers
        shell: bash -l {0}
        run:  |
          #source ~/.bashrc
          echo "1"
          export TERM=xterm #For interactive shell, otherwise problems for colors
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          echo "2"
          #source ~/opt/scifor/gnu/*/bin/scifor_config_user.sh
          #source ~/opt/dmft_tools/gnu/*/bin/dmft_tools_config_user.sh
          #source ~/opt/dmft_ed/gnu/*/etc/dmft_ed_config.sh
          #source ~/opt/slave_spins/gnu/*/etc/slave_spins_config.sh
          echo "3"
          echo "$( ls )"
          ./inst_Drivers.sh






  test-macos-10_15:
    runs-on: macos-10.15

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#Reinstall gfortran
      - name: Required compiler
        run:  brew reinstall gfortran
      - name: gfortran-info
        run: gfortran --version

#Install BLAS and LAPACK
      - name: blas-n-lapack-install
        run: brew install lapack openblas

#Install OpenMPI
      - name: install-openmpi
        run: brew install openmpi

#Set up SciFortran
      - name: Cloning SciFortran
        run: git clone https://github.com/QcmPlab/SciFortran.git scifor
      - name: Install SciFortran
        run: ./inst_scifor.sh

#Set up DMFTtools
      - name: Cloning DMFTtools
        run: git clone https://github.com/QcmPlab/DMFTtools.git DMFTtools
      - name: Install DMFTtools
        run: ./inst_DMFTtools.sh

#Set up LIB_DMFT_ED
      - name: Cloning LIB_DMFT_ED
        run: git clone https://github.com/QcmPlab/LIB_DMFT_ED.git LIB_DMFT_ED
      - name: Install LIB_DMFT_ED
        run: ./inst_LIB_DMFT_ED.sh


#Set up Slave_Spins
      - name: Cloning Slave_Spins
        run: git clone https://github.com/QcmPlab/Slave-Spins Slave_Spins
      - name: Install Slave_Spins
        run: ./inst_Slave_Spins.sh


#Set up Drivers
      - name: Cloning Drivers
        run: git clone https://github.com/QcmPlab/Driver-Database.git Driver-Database
      - name: Install Drivers
        run:   |
          source ~/.bashrc
          echo "1"
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          export SCIFORVER=$( ls ~/opt/scifor/gnu )
          export DMFTVER=$(   ls ~/opt/dmft_tools/gnu )
          export LIBEDVER=$(  ls ~/opt/dmft_ed/gnu )
          export SSPINVER=$(  ls ~/opt/slave_spins/gnu )
          echo "2"
          source ~/opt/scifor/gnu/$(SCIFORVER)/bin/scifor_config_user.sh
          source ~/opt/dmft_tools/gnu/$(DMFTVER)/bin/dmft_tools_config_user.sh
          source ~/opt/dmft_ed/gnu/$(LIBEDVER)/etc/dmft_ed_config.sh
          source ~/opt/dmft_ed/gnu/$(SSPINVER)/etc/slave_spins_config.sh
          echo "3"
          export GLOB_INC=$( pkg-config --cflags dmft_ed dmft_tools scifor slave_spins)
          export GLOB_LIB=$( pkg-config --libs   dmft_ed dmft_tools scifor slave_spins | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          ./inst_Drivers.sh

#Testing
      - name: Building tests
        run:   |
          source ~/.bashrc
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          export SCIFORVER=$( ls ~/opt/scifor/gnu )
          export DMFTVER=$(   ls ~/opt/dmft_tools/gnu )
          export LIBEDVER=$(  ls ~/opt/dmft_ed )
          source ~/opt/scifor/gnu/$(SCIFORVER)/bin/scifor_config_user.sh
          source ~/opt/dmft_tools/gnu/$(DMFTVER)/bin/dmft_tools_config_user.sh
          source ~/opt/dmft_ed/gnu/$(LIBEDVER)/etc/dmft_ed_config.sh
          export GLOB_INC=$( pkg-config --cflags dmft_ed dmft_tools scifor)
          export GLOB_LIB=$( pkg-config --libs   dmft_ed dmft_tools scifor | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          make all
        
      - name: Testing...
        run: make test

