
name: Scheduled CI workflow

on:
  schedule:
#             min - hour - day of month - month - day of week
    - cron:  '0 9 1,15 * *' #Mon and Thu of May at 9:00 and 17:00

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-QcmP:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:

#********* SETUP PART **********

# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

# Uses pre-defined fortran setup
      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:	  
          compiler: gcc
          version: 9

# QcmPlab setup
      - uses: SamueleGiuli/CIproject_QcmP/.github/actions@main
        with:
          pack-type: open

#********* BUILD PART **********

# Build SciFortran
      - name: Cloning SciFortran
        run: git clone https://github.com/QcmPlab/SciFortran.git scifor
      - name: Install SciFortran
        run: ./inst_scifor.sh

# Build DMFTtools
      - name: Cloning DMFTtools
        run: git clone https://github.com/QcmPlab/DMFTtools.git DMFTtools
      - name: Install DMFTtools
        run: ./inst_DMFTtools.sh

# Build LIB_DMFT_ED
      - name: Cloning LIB_DMFT_ED
        run: git clone https://github.com/QcmPlab/LIB_DMFT_ED.git LIB_DMFT_ED
      - name: Install LIB_DMFT_ED
        run: ./inst_LIB_DMFT_ED.sh

# Build Slave_Spins
      - name: Cloning Slave_Spins
        run: git clone https://github.com/QcmPlab/Slave-Spins Slave_Spins
      - name: Install Slave_Spins
        run: ./inst_Slave_Spins.sh

#******** TESTING PART ********

# Testing
      - name: Building tests
        run:  |
          source ~/.QcmP_source
          export PKG_CONFIG_PATH=~/.pkgconfig.d
          export GLOB_INC=$( pkg-config --cflags dmft_ed dmft_tools scifor slave_spins)
          export GLOB_LIB=$( pkg-config --libs   dmft_ed dmft_tools scifor slave_spins | sed  "s/;/ /g"  | sed 's/\\/  /g' )
          make all

      - name: Testing...
        run: make test